### ISSUE TITLE
Deprecation notice for VisibilitySensor

### ISSUE THREAD

**Issue by genox** [imbhargav5/react-lazy-progressive-image#34]
Hi,

Please update dependency react-visibility-sensor to current. Current version used by react-lazy-progressive-image is react-visibility-sensor@3.14.0 while the most recent version is @5.1.1. This causes a deprecation notice (unsafe lifecycle).  react-visibility-sensor changed their lifecycle implementation around @4.0.0, according to the issue log over there.

Thanks :)

**Comment by imbhargav5** [comment]
Fixed it :)
